# containers/base/environment.yaml
name: base-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pysam>=0.23.3
  - numpy>=2.3.3
  - cyvcf2>=0.31.1
  - hatchling>=1.20
  - uv
  - pip
