# .github/workflows/docker.yml
name: Build & Push Containers

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]     # push versioned tags
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: ngs-base
            file: containers/base/Dockerfile
            tag: latest
          - name: cutadapt
            file: containers/cutadapt/Dockerfile
            tag: "5.1"
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.image.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.file }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
